# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - test

pool:
  vmImage: ubuntu-latest

variables:
  imageName: "chatbot-xm-back"
  registryServiceConnection: "chatbotxmregistryconnection"
  repository: "chatbot-xm-back"

steps:
  - script: |
      echo "##vso[task.setvariable variable=dockerImageName;]$(imageName)"
    displayName: "Set Docker Image Name"

  - task: Docker@2
    displayName: Login container registry
    inputs:
      command: login
      containerRegistry: $(registryServiceConnection)

  - task: Docker@2
    displayName: build image
    inputs:
      containerRegistry: $(registryServiceConnection)
      repository: $(repository)
      command: "build"
      Dockerfile: "**/Dockerfile"

  - task: Docker@2
    displayName: Push image to acr
    inputs:
      containerRegistry: $(registryServiceConnection)
      repository: $(repository)
      command: push

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Experiencia digital  - 02(ee8db988-bfd6-4b1a-9dd6-043bc27e952c)'
      appType: 'webAppContainer'
      WebAppName: 'chatbotxm-back'
      DockerNamespace: 'chatbotxmregistry.azurecr.io'
      DockerRepository: '$(repository):$(Build.BuildId)'

